name: Checks
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    format:
        name: Check code formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
            - name: Uninstall native dependency - not needed for formatter
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: npm ci
            - name: Run Prettier check
              run: |
                  node --run format:check
                  echo "✅ Code formatting is correct!"
    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
            - name: Uninstall native dependency - not needed for linting
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: |
                  npm ci
            - name: Run ESLint
              run: |
                  node --run lint
                  echo "✅ Linting passed successfully!"
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
            - name: Uninstall native dependency - not needed for linting
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: |
                  npm ci
            - name: Run ESLint
              run: |
                  node --run test:coverage
                  echo "✅ Linting passed successfully!"

#    tsc:
#        name: TS type check
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v6
#            - name: Set up Node.js
#              uses: actions/setup-node@v6
#              with:
#                  node-version: "24"
#            - name: Uninstall native dependency - not needed for linting
#              run: |
#                  npm uninstall node-libgpiod
#            - name: Install dependencies
#              run: |
#                  npm ci
#            - name: Run ESLint
#              run: |
#                  node --run tsc
#                  echo "✅ Type check passed successfully!"
