name: Checks
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    format:
        name: Check code formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
            - name: Set up Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
              with:
                  node-version-file: ".nvmrc"
            - name: Uninstall native dependency - not needed for formatter
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: npm ci --ignore-scripts
            - name: Run Prettier check
              run: |
                  node --run format:check
                  echo "✅ Code formatting is correct!"
    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
            - name: Set up Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
              with:
                  node-version-file: ".nvmrc"
            - name: Uninstall native dependency - not needed for linting
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: |
                  npm ci --ignore-scripts
            - name: Run ESLint
              run: |
                  node --run lint
                  echo "✅ Linting passed successfully!"
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
            - name: Set up Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
              with:
                  node-version-file: ".nvmrc"
            - name: Uninstall native dependency - not needed for linting
              run: |
                  npm uninstall node-libgpiod
            - name: Install dependencies
              run: |
                  npm ci --ignore-scripts
            - name: Run ESLint
              run: |
                  node --run test:coverage
                  echo "✅ Tests passed successfully!"

            - name: SonarCloud Scan
              uses: SonarSource/sonarqube-scan-action@v6.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#    tsc:
#        name: TS type check
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
#            - name: Set up Node.js
#              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
#              with:
#                  node-version-file: ".nvmrc"
#            - name: Uninstall native dependency - not needed for linting
#              run: |
#                  npm uninstall node-libgpiod
#            - name: Install dependencies
#              run: |
#                  npm ci
#            - name: Run ESLint
#              run: |
#                  node --run tsc
#                  echo "✅ Type check passed successfully!"
